const mysql = require('mysql2/promise');

const replacements = {
  // Các cụm từ hỏi
  "i?n vo ch? tr?ng": "Điền vào chỗ trống",
  "T? d?ng nghia c?a": "Từ đồng nghĩa của",
  "T? tri nghia c?a": "Từ trái nghĩa của",
  "T? no tri nghia v?i": "Từ nào trái nghĩa với",
  "T? no d?ng nghia v?i": "Từ nào đồng nghĩa với",
  "c nghia l g": "có nghĩa là gì",
  "thu?c ch? d? no": "thuộc chủ đề nào",
  "thu?c nhm no": "thuộc nhóm nào",
  "t? no ph h?p nh?t": "từ nào phù hợp nhất",
  "t? no ph h?p": "từ nào phù hợp",
  "c?m t? no dng": "cụm từ nào đúng",
  "di?n t? ph h?p": "điền từ phù hợp",
  "di?n t?": "điền từ",
  "p n": "Đáp án",
  "S? khc bi?t gi?a": "Sự khác biệt giữa",
  "Khi no b?n dng": "Khi nào bạn dùng",
  "Mu 'white' l mu g": "Màu 'white' là màu gì",
  "du?c dng d? lm g": "được dùng để làm gì",
  "l noi dng d? lm g": "là nơi dùng để làm gì",
  "c nghia l g khi dng lm mu s?c": "có nghĩa là gì khi dùng làm màu sắc",

  // Các từ đơn lẻ (A, B, C, D)
  "T?m bi?t": "Tạm biệt",
  "Xin cho": "Xin chào",
  "C?m on": "Cảm ơn",
  "Xin l?i": "Xin lỗi",
  "Khi g?p ai d": "Khi gặp ai đó",
  "Ci bn": "Cái bàn",
  "Quy?n sch": "Quyển sách",
  "Cy bt": "Cây bút",
  "T? gi?y": "Tờ giấy",
  "Gio vin": "Giáo viên",
  "Bc si": "Bác sĩ",
  "H?c sinh": "Học sinh",
  "B?n b": "Bạn bè",
  "Tru?ng h?c": "Trường học",
  "B?nh vi?n": "Bệnh viện",
  "Vn phng": "Văn phòng",
  "i?u nh?y": "Điệu nhảy",
  "Bi ht": "Bài hát",
  "m nh?c": "Âm nhạc",
  "Nh?c c?": "Nhạc cụ",
  "Nh?y ma": "Nhảy múa",
  "Ngi xu?ng": "Ngồi xuống",
  "ng d?y": "Đứng dậy",
  "N?m xu?ng": "Nằm xuống",
  "Ch?y di": "Chạy đi",
  "Xe d?p": "Xe đạp",
  "Xe bus": "Xe buýt",
  "Tu h?a": "Tàu hỏa",
  "Bng hoa": "Bông hoa",
  "Cy c?": "Cây cỏ",
  "Cy g?/cy xanh": "Cây gỗ/cây xanh",
  "L cy": "Lá cây",
  "Cy xanh": "Cây xanh",
  "M?t trang": "Mặt trăng",
  "B?u tr?i": "Bầu trời",
  "Ngi sao": "Ngôi sao",
  "m my": "Đám mây",
  "Bang/d l?nh": "Băng/đá lạnh",
  "Thnh ph?": "Thành phố",
  "Xanh l": "Xanh lá",
  "Xanh duong": "Xanh dương",
  "?": "Đỏ",
  "Vng": "Vàng",
  "Con ch": "Con chó",
  "Con mo": "Con mèo",
  "Con c": "Con cá",
  "Con th?": "Con thỏ",
  "Con h?": "Con hổ",
  "Con voi": "Con voi",
  "Con chu?t": "Con chuột",
  "Con chim": "Con chim",
  "Con g?u": "Con gấu",
  "Con si": "Con sói",
  "Con su t?": "Con sư tử",
  "Mu d?": "Màu đỏ",
  "Mu xanh": "Màu xanh",
  "Mu vng": "Màu vàng",
  "Mu tm": "Màu tím",
  "Mu h?ng": "Màu hồng",
  "Mu den": "Màu đen",
  "Mu tr?ng": "Màu trắng",
  "Mu xm": "Màu xám",
  "Mu nu": "Màu nâu",
  "Mu cam": "Màu cam",
  "Vy d?m": "Váy đầm",
  "o khoc": "Áo khoác",
  "o so mi": "Áo sơ mi",
  "Qu?n short": "Quần short",
  "Ci mu": "Cái mũ",
  "Ci ti": "Cái túi",
  "Ci vng": "Cái vòng",
  "Che mua": "Che mưa",
  "c sch": "Đọc sách",
  "Ch?nh th? l?c": "Chỉnh thị lực",
  "C? B v C": "Cả B và C",
  "Tri cy": "Trái cây",
  "Rau c?": "Rau củ",
  "Th?t": "Thịt",
  "Ng c?c": "Ngũ cốc",
  "Bnh m": "Bánh mì",
  "Sp / Canh": "Súp / Canh",
  "Cm": "Cơm",
  "M": "Mì",
  "u?ng": "Đường",
  "Mu?i": "Muối",
  "Tiu": "Tiêu",
  "D?u": "Dầu",
  "Ci giu?ng": "Cái giường",
  "Ci gh?": "Cái ghế",
  "Ci t?": "Cái tủ",
  "Phng ng?": "Phòng ngủ",
  "Phng khch": "Phòng khách",
  "Nh b?p": "Nhà bếp",
  "Phng t?m": "Phòng tắm",
  "N?u an": "Nấu ăn",
  "H?c bi": "Học bài",
  "C?a s?": "Cửa sổ",
  "Guong": "Gương",
  "i?n tho?i": "Điện thoại",
  "My in": "Máy in",
  "Mn hnh": "Màn hình",
  "Ph?n m?m": "Phần mềm",
  "My tnh": "Máy tính",
  "Tn dang nh?p": "Tên đăng nhập",
  "M?t kh?u": "Mật khẩu",
  "Ti kho?n": "Tài khoản",
  "Tru?ng m?u gio": "Trường mẫu giáo",
  "Tru?ng ti?u h?c": "Trường tiểu học",
  "Tru?ng trung h?c": "Trường trung học",
  "Tru?ng d?i h?c": "Trường đại học",
  "Bi t?p": "Bài tập",
  "K? thi": "Kỳ thi",
  "L?p h?c": "Lớp học",
  "Sch gio khoa": "Sách giáo khoa",
  "Vi?c nh": "Việc nhà",
  "Bi t?p v? nh": "Bài tập về nhà",
  "i?m s?": "Điểm số",
  "Hi?u sch": "Hiệu sách",
  "Thu vi?n": "Thư viện",
  "Chi ph": "Chi phí",
  "Thu?": "Thuế",
  "Luong": "Lương",
  "Ti?n thu?ng": "Tiền thưởng",
  "Ngn hng": "Ngân hàng",
  "Buu di?n": "Bưu điện",
  "Siu th?": "Siêu thị",
  "Ti?c": "Tiệc",
  "Cu?c h?p": "Cuộc họp",
  "Bu?i ha nh?c": "Buổi hòa nhạc",
  "Xe l?a": "Xe lửa",
  "Tu thuy?n": "Tàu thuyền",
  "My bay": "Máy bay",
  "V tu": "Vé tàu",
  "B?n d?": "Bản đồ",
  "H? chi?u": "Hộ chiếu",
  "Th? can cu?c": "Thẻ căn cước",
  "B? phim": "Bộ phim",
  "Tr choi": "Trò chơi",
  "Tri?n lm": "Triển lãm",
  "Cng vi?c": "Công việc",
  "S? thch": "Sở thích",
  "Mn h?c": "Môn học",
  "Ngh? nghi?p": "Nghề nghiệp",
  "K? ngh?": "Kỳ nghỉ",
  "Bu?i h?c": "Buổi học",
  "Bo": "Bão",
  "Lu l?t": "Lũ lụt",
  "ng d?t": "Động đất",
  "Ni l?a": "Núi lửa",
  "ng c?": "Đồng cỏ",
  "Sa m?c": "Sa mạc",
  "R?ng": "Rừng",
  "?i duong": "Đại dương",
  "Gi nh?": "Gió nhẹ",
  "Mua phn": "Mưa phùn",
  "Suong m": "Sương mù",
  "Giao ti?p b?ng m?t": "Giao tiếp bằng mắt",
  "Nh?m m?t": "Nhắm mắt",
  "Nhn xu?ng": "Nhìn xuống",
  "Lu n lu n": "Luôn luôn",
  "Kh ng bao gi?": "Không bao giờ",
  "  i khi": "Đôi khi",
  "R?t": "Rất",
  "Ch?c ch?n": "Chắc chắn",
  "C  l?": "Có lẽ",
  "  t ": "Ô tô",
  "  p  n": "Đáp án",
  " i?n v o": "Điền vào",
  "T? tr i nghia": "Từ trái nghĩa"
};

async function fixGrammar() {
  const pool = mysql.createPool({
    host: 'localhost',
    user: 'root',
    password: '123456',
    database: 'minlish_db',
    charset: 'utf8mb4'
  });

  console.log('Đang kết nối database để sửa lỗi quiz_question...');
  
  const [rows] = await pool.query('SELECT id, quiz_question FROM words WHERE quiz_question IS NOT NULL');
  
  let updated = 0;
  for (const row of rows) {
    let newText = row.quiz_question;
    
    // Áp dụng tất cả các quy tắc thay thế
    for (const [bad, good] of Object.entries(replacements)) {
      if (newText.includes(bad)) {
        newText = newText.split(bad).join(good);
      }
    }
    
    if (newText !== row.quiz_question) {
      await pool.execute('UPDATE words SET quiz_question = ? WHERE id = ?', [newText, row.id]);
      updated++;
      console.log(`✓ ID ${row.id}: ${newText}`);
    }
  }

  console.log(`\n✅ Đã fix ${updated} quiz questions!`);
  process.exit(0);
}

fixGrammar().catch(err => { console.error('Lỗi:', err.message); process.exit(1); });
